name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install your project dependencies

      - name: Run Tests
        run: |
          test

      - name: Build Sphinx Documentation
        run: |
          make docs/ html  # Or any other Sphinx build command

      - name: Deploy Documentation
        run: |
          # Copy the generated HTML to a deployment destination (e.g., GitHub Pages)
          cp -r docs/build/html/* 
