name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install your project dependencies
  
      - name: Run Tests
        run: |
          python test.py 
          
      - name: Install Sphinx
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Sphinx Documentation
        run: |
          make html

      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -r docs/build/html/* gh-pages/
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
