name: CI/CD Pipeline

on:
  push:
    branches:
      - master  # Change this to your repository's default branch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Set Up Python
        uses: actions/setup-python@v2
        with:
          python-version: 3.x

      - name: Install Dependencies
        run: |
          pip install -r requirements.txt  # Install your project dependencies
  
      - name: Run Tests
        run: |
          python test.py 
          
      - name: Install Sphinx
        run: |
          pip install sphinx
          pip install sphinx-rtd-theme
          
      - name: Checkout Repository
        uses: actions/checkout@v2
        
      - name: Build Sphinx Documentation
        run: |
          make html
      
      - name: Deploy to GitHub Pages
        run: |
          mkdir gh-pages
          cp -r build/html/* gh-pages/
        env:
          GITHUB_TOKEN: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN  }}
      
      - name: Push to gh-pages Branch
        uses: actions/github-script@v4
        with:
          github-token: ${{ secrets.MY_PERSONAL_ACCESS_TOKEN }}
          script: |
            const fs = require('fs');
            const path = require('path');
            const { execSync } = require('child_process');
      
            const repoPath = process.env.GITHUB_REPOSITORY;
            const ghPagesPath = path.join(process.cwd(), 'gh-pages');
      
            // Set the Git configuration temporarily
            execSync(`git config user.name "GitHub Actions"`);
            execSync(`git config user.email "actions@github.com"`);
      
            // Commit and push changes
            execSync(`cd ${ghPagesPath}`);
            execSync(`git init`);
            execSync(`git add .`);
            execSync(`git commit -m "Deploy Sphinx documentation"`);
            execSync(`git push --force "https://${process.env.GITHUB_TOKEN}@github.com/${repoPath}.git" master:gh-pages`);
